name: timefocus
description: "TimeFocus"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.9

  # State Management
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  # Freezed
  freezed_annotation: ^3.1.0
  # JSON Serialization
  json_annotation: ^4.12.0
  # Navigation
  go_router: ^17.3.0
  # DI
  get_it: ^9.2.1
  injectable: ^3.0.0
  # Database
  drift: ^2.34.0 # Локальная SQLite база 
  drift_flutter: ^0.3.1
  sqlite3_flutter_libs: ^0.6.0
  # Local Notifications
  flutter_local_notifications: ^22.0.1
  flutter_timezone: ^5.1.0
  timezone: ^0.11.1
  # UI
  font_awesome_flutter: ^11.0.0 # для расширенных иконок активностей
  flutter_colorpicker: ^1.1.0  # Выбор цветов для активностей
  fl_chart: ^1.2.0
  # Permission
  permission_handler: ^12.0.3
  # Device info
  device_info_plus: ^13.2.0
  package_info_plus: ^10.2.1
  # Images
  flutter_svg: ^2.3.0
  # Toast
  toastification: ^3.2.0
  # Splash
  flutter_native_splash: ^2.4.8
  # Utils
  collection: ^1.19.1
  path_provider: ^2.1.6
  path: ^1.9.1
  logger: ^2.7.0
  vibration: ^3.2.0
  url_launcher: ^6.3.2
  app_settings: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  injectable_generator: ^3.0.2
  drift_dev: ^2.34.0
  flutter_gen_runner: ^5.15.0
  flutter_gen: 5.15.0
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0
  # Test
  bloc_test: ^10.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  generate: true

  config:
    enable-swift-package-manager: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf

flutter_gen:
  line_length: 100
